--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/pjz9n-pm-pl/CoinShopPlus
build-by-default: true
branches:
  - master
projects:
  CoinShopPlus:
    libs:
      - src: dktapps-pm-pl/pmforms/pmforms
        version: 1.0.0
      - src: pjz9n-pm-pl/pmforms-addon/pmforms-addon
        version: 1.0.0
      - src: PJZ9n/MoneyConnector/MoneyConnector
        version: 2.3.0
      - src: CortexPE/Commando/Commando
        version: 2.1.1
...
